title: Adriano Augusto Antongiovanni # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist Intern at Empiricus | Mechatronics Engineering Student |
  Data Science and Artificial Intelligence Enthusiastic
  <br><br>
  I am an engineering student enthusiastic of new technologies, such as AI, Big Data and Machine Learning. I have experience in team leadership and management at Projeto Jupiter, a group of more than 90 students dedicated do launch experiemtnal rockets in international competitions. I also have research experience in the fild of biomechatronics, in a project sponsored by the brasilian goverment. 
  <br><br>
  <a href="https://www.linkedin.com/in/adriano-augusto-antongiovanni/">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
